name: Helm Chart Deployment

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          version: '416.0.0'
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GKE_SA_KEY }}


      - name: Install Helm
        run: |
          curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash

      - name: Deploy
        run: |
          gcloud container clusters get-credentials my-gke-cluster \
            --zone us-central1-a \
            --project gke-cluster-426323
          helm upgrade --install my-ml-api ./my-ml-api \
            --wait
          kubectl rollout status deployment/my-ml-api
          kubectl get services -o wide
