name: Deploy Helm Chart

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Kubeconfig
      run: |
        mkdir -p $HOME/.kube
        echo "${{ secrets.KUBECONFIG_CONTENT }}" > $HOME/.kube/config
      env:
        KUBECONFIG: $HOME/.kube/config

    - name: Install kubectl
      run: |
        curl -LO "https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl"
        chmod +x ./kubectl
        sudo mv ./kubectl /usr/local/bin/kubectl

    - name: Verify Kubernetes connection
      run: |
        kubectl cluster-info
      env:
        KUBECONFIG: $HOME/.kube/config

    - name: Install Helm
      run: |
        curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

    - name: Deploy Helm Chart
      run: |
        helm install my-ml-api ./my-ml-api
      env:
        KUBECONFIG: $HOME/.kube/config
