name: Helm Chart Deployment

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          version: '416.0.0'

      - name: Authenticate to GKE
        run: |
          echo "${{ secrets.GKE_SA_KEY }}" | base64 --decode > ${HOME}/gcp-key.json
          gcloud auth activate-service-account --key-file=${HOME}/gcp-key.json
          gcloud config set project gke-cluster-426323
          gcloud config set compute/zone us-central1-a
          gcloud container clusters get-credentials my-gke-cluster

      - name: Install Helm
        run: |
          curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash

      - name: Deploy
        run: |
          helm upgrade --install my-ml-api ./my-ml-api \
            --wait
          kubectl rollout status deployment/my-ml-api
          kubectl get services -o wide
