name: CI/CD Pipeline

on:
  push:
    branches:
      - env-testing

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Build and push Docker image
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: docker.io/warhammer21/helmchart:latest

  deploy-dev:
    runs-on: ubuntu-latest
    needs: build

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GKE_SA_KEY }}

    - name: Get GKE Credentials
      uses: google-github-actions/get-gke-credentials@v1
      with:
        cluster_name: ${{ secrets.GKE_CLUSTER_NAME }}
        location: ${{ secrets.GKE_CLUSTER_ZONE }}
        project_id: ${{ secrets.GKE_PROJECT_ID }}

    - name: Install Helm
      run: |
        curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash

    - name: Deploy to Dev
      run: |
        helm upgrade --install my-ml-api-dev ./my-ml-api --namespace dev --values ./my-ml-api/values-dev.yaml --wait
        kubectl rollout status deployment/my-ml-api-dev --namespace dev
        kubectl get services --namespace dev -o wide

    - name: Run tests
      run: |
        # Simple test: linting the Kubernetes manifest files
        echo "Running linting tests..."
        helm lint ./my-ml-api
        echo "Linting tests completed."

  deploy-prod:
    runs-on: ubuntu-latest
    needs: deploy-dev

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GKE_SA_KEY }}

    - name: Get GKE Credentials
      uses: google-github-actions/get-gke-credentials@v1
      with:
        cluster_name: ${{ secrets.GKE_CLUSTER_NAME }}
        location: ${{ secrets.GKE_CLUSTER_ZONE }}
        project_id: ${{ secrets.GKE_PROJECT_ID }}

    - name: Install Helm
      run: |
        curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash

    - name: Deploy to Prod
      run: |
        helm upgrade --install my-ml-api-prod ./my-ml-api --namespace prod --values ./my-ml-api/values-prod.yaml --wait
        kubectl rollout status deployment/my-ml-api-prod --namespace prod
        kubectl get services --namespace prod -o wide

    - name: Expose Service
      run: |
        kubectl expose deployment my-ml-api-prod --namespace prod --type=LoadBalancer --name=my-ml-api-service --port=80 --target-port=8000
        kubectl get services my-ml-api-service --namespace prod -o wide
